# -*- coding: utf-8 -*-
"""etl_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OEoLSmByEQzCaQPs5h1k4urx6qFmBggK
"""

import pandas as pd
import logging
from sqlalchemy import create_engine, text

# Configuración de logging (formato simple para Colab)
logging.basicConfig(level=logging.INFO, format="%(message)s")

# Parámetros de conexión
HOST = "aurora-mod4.cluster-cvqrttoqiwks.us-east-1.rds.amazonaws.com"
PORT = 5432
USER = "postgres"
PASSWORD = "D1pl0m4d0"
DATABASE = "northwind"

engine = create_engine(f"postgresql+psycopg2://{USER}:{PASSWORD}@{HOST}:{PORT}/{DATABASE}")

def extract(engine):
    try:
        logging.info("Extrayendo datos del OLTP...")
        customers = pd.read_sql("SELECT * FROM northwind_oltp.customers", engine)
        products = pd.read_sql("""
            SELECT p.*, c.category_name, c.description AS category_desc,
                   s.company_name AS supplier_name, s.country AS supplier_country, s.city AS supplier_city
            FROM northwind_oltp.products p
            JOIN northwind_oltp.categories c ON p.category_id = c.category_id
            JOIN northwind_oltp.suppliers s ON p.supplier_id = s.supplier_id
        """, engine)
        employees = pd.read_sql("SELECT * FROM northwind_oltp.employees", engine)
        shippers = pd.read_sql("SELECT * FROM northwind_oltp.shippers", engine)
        orders = pd.read_sql("SELECT * FROM northwind_oltp.orders", engine)
        order_details = pd.read_sql("SELECT * FROM northwind_oltp.order_details", engine)
        print("✅ Extracción completada")
        return customers, products, employees, shippers, orders, order_details
    except Exception as e:
        logging.error("Error en extracción: %s", e)
        raise

def transform(customers, products, employees, shippers, orders, order_details):
    logging.info("Transformando datos...")
    orders["order_date"] = pd.to_datetime(orders["order_date"], errors="coerce")
    orders["required_date"] = pd.to_datetime(orders["required_date"], errors="coerce")
    orders["shipped_date"] = pd.to_datetime(orders["shipped_date"], errors="coerce")

    orders["order_date_key"] = orders["order_date"].dt.strftime("%Y%m%d").astype(int)
    orders["required_date_key"] = orders["required_date"].dt.strftime("%Y%m%d").astype(int)
    orders["shipped_date_key"] = orders["shipped_date"].dt.strftime("%Y%m%d").astype("Int64")

    fact_sales = order_details.merge(orders, on="order_id", how="left")
    products["discontinued"] = products["discontinued"].astype(bool)
    employees["full_name"] = employees["first_name"] + " " + employees["last_name"]

    all_dates = pd.concat([orders["order_date"], orders["required_date"], orders["shipped_date"]]).dropna().drop_duplicates().sort_values()
    dim_date = pd.DataFrame({
        "date_key": all_dates.dt.strftime("%Y%m%d").astype(int),
        "full_date": all_dates
    })
    dim_date["year"] = dim_date["full_date"].dt.year
    dim_date["quarter"] = dim_date["full_date"].dt.quarter
    dim_date["month_number"] = dim_date["full_date"].dt.month
    dim_date["month_name"] = dim_date["full_date"].dt.strftime("%B")
    dim_date["week_of_year"] = dim_date["full_date"].dt.isocalendar().week
    dim_date["day_of_month"] = dim_date["full_date"].dt.day
    dim_date["day_of_week_number"] = dim_date["full_date"].dt.dayofweek + 1
    dim_date["day_of_week_name"] = dim_date["full_date"].dt.strftime("%A")
    dim_date["is_weekend"] = dim_date["day_of_week_number"].isin([6,7])

    print("✅ Transformación completada")
    return customers, products, employees, shippers, dim_date, fact_sales

def load(engine, customers, products, employees, shippers, dim_date, fact_sales):
    try:
        logging.info("Limpiando tablas del DWH...")
        with engine.begin() as conn:
            conn.execute(text("TRUNCATE TABLE northwind_dwh.fact_sales CASCADE;"))
            conn.execute(text("TRUNCATE TABLE northwind_dwh.dim_customer CASCADE;"))
            conn.execute(text("TRUNCATE TABLE northwind_dwh.dim_product CASCADE;"))
            conn.execute(text("TRUNCATE TABLE northwind_dwh.dim_employee CASCADE;"))
            conn.execute(text("TRUNCATE TABLE northwind_dwh.dim_shipper CASCADE;"))
            conn.execute(text("TRUNCATE TABLE northwind_dwh.dim_date CASCADE;"))

        logging.info("Cargando dimensiones...")
        customers[["customer_id","company_name","contact_name","contact_title","city","region","postal_code","country"]].to_sql("dim_customer", engine, schema="northwind_dwh", if_exists="append", index=False)
        products[["product_id","product_name","category_id","category_name","category_desc","supplier_id","supplier_name","supplier_country","supplier_city","discontinued"]].to_sql("dim_product", engine, schema="northwind_dwh", if_exists="append", index=False)
        employees[["employee_id","full_name","title","city","country","region","hire_date"]].to_sql("dim_employee", engine, schema="northwind_dwh", if_exists="append", index=False)
        shippers[["shipper_id","company_name","phone"]].to_sql("dim_shipper", engine, schema="northwind_dwh", if_exists="append", index=False)
        dim_date.to_sql("dim_date", engine, schema="northwind_dwh", if_exists="append", index=False)

        logging.info("Mapeando surrogate keys...")
        dim_customer = pd.read_sql("SELECT customer_key, customer_id FROM northwind_dwh.dim_customer", engine)
        fact_sales = fact_sales.merge(dim_customer, on="customer_id", how="left")
        dim_product = pd.read_sql("SELECT product_key, product_id FROM northwind_dwh.dim_product", engine)
        fact_sales = fact_sales.merge(dim_product, on="product_id", how="left")
        dim_employee = pd.read_sql("SELECT employee_key, employee_id FROM northwind_dwh.dim_employee", engine)
        fact_sales = fact_sales.merge(dim_employee, on="employee_id", how="left")
        dim_shipper = pd.read_sql("SELECT shipper_key, shipper_id FROM northwind_dwh.dim_shipper", engine)
        fact_sales = fact_sales.merge(dim_shipper, left_on="ship_via", right_on="shipper_id", how="left")

        logging.info("Cargando fact_sales...")
        fact_sales[["order_id","customer_key","product_key","employee_key","shipper_key","order_date_key","required_date_key","shipped_date_key","quantity","unit_price","discount"]].to_sql("fact_sales", engine, schema="northwind_dwh", if_exists="append", index=False)

        print("✅ Carga completada")
    except Exception as e:
        logging.error("Error en carga: %s", e)
        raise

def verify(engine):
    logging.info("Verificando contenido del DWH...")
    with engine.connect() as conn:
        fact_count = conn.execute(text("SELECT COUNT(*) FROM northwind_dwh.fact_sales")).scalar()
        cust_count = conn.execute(text("SELECT COUNT(*) FROM northwind_dwh.dim_customer")).scalar()
        prod_count = conn.execute(text("SELECT COUNT(*) FROM northwind_dwh.dim_product")).scalar()
        emp_count = conn.execute(text("SELECT COUNT(*) FROM northwind_dwh.dim_employee")).scalar()
        ship_count = conn.execute(text("SELECT COUNT(*) FROM northwind_dwh.dim_shipper")).scalar()
        date_count = conn.execute(text("SELECT COUNT(*) FROM northwind_dwh.dim_date")).scalar()
        print(f"🔍 fact_sales={fact_count} | dim_customer={cust_count} | dim_product={prod_count} | dim_employee={emp_count} | dim_shipper={ship_count} | dim_date={date_count}")

        invalid_prod = conn.execute(text("""
            SELECT COUNT(*)
            FROM northwind_dwh.fact_sales f
            LEFT JOIN northwind_dwh.dim_product p ON f.product_key = p.product_key
            WHERE p.product_key IS NULL
        """)).scalar()
        print("🔍 fact_sales con product_key inválido =", invalid_prod)

        total_oltp = conn.execute(text("SELECT SUM(unit_price * quantity * (1 - discount)) FROM northwind_oltp.order_details")).scalar()
        total_dwh = conn.execute(text("SELECT SUM(line_total) FROM northwind_dwh.fact_sales")).scalar()
        print("🔍 Total ventas OLTP =", total_oltp, "| Total ventas DWH =", total_dwh)

def main():
    # 1. Extract
    customers, products, employees, shippers, orders, order_details = extract(engine)

    # 2. Transform
    customers, products, employees, shippers, dim_date, fact_sales = transform(
        customers, products, employees, shippers, orders, order_details
    )

    # 3. Load
    load(engine, customers, products, employees, shippers, dim_date, fact_sales)

    # 4. Verify
    verify(engine)

# Ejecutar el pipeline
if __name__ == "__main__":
    main()